#!/bin/bash

echo "all variables passed to the script:$@"
echo "all variables passed to the script:$*"
echo "script name:$0"
echo " current directory:$PWD"
echo " who is running this:$USER"
echo "Home directory of user:$HOME"
echo "PID of this script:$$"
sleep 10 &
echo "PID of the last command in the background is :$!"
